Added comments to all workflows

diff --git a/.github/workflows/bump-version-file.yml b/.github/workflows/bump-version-file.yml
--- a/.github/workflows/bump-version-file.yml
+++ b/.github/workflows/bump-version-file.yml
@@ -1,3 +1,7 @@
+# This workflow is used to do a major/minor version bump to the `VERSION` file,
+# through a comment on the PR.
+# This is not done automatically because users may want to modify their config
+# based on the result of the reproducibility check.
 name: VERSION
 on:
   issue_comment:
@@ -7,6 +11,7 @@ on:
 jobs:
   bump-version:
     name: Bump
+    # Bump the `VERSION` file if the comment is made on a PR and starts with '!bump'
     if: github.event.issue.pull_request && startsWith(github.event.comment.body, '!bump')
     runs-on: ubuntu-latest
     permissions:
@@ -14,22 +19,18 @@ jobs:
       pull-requests: write
     env:
       RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      GH_TOKEN: ${{ secrets.GH_COMMIT_CHECK_TOKEN }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
           token: ${{ secrets.GH_COMMIT_CHECK_TOKEN }}
 
-      - name: Checkout Associated PR
-        env:
-          GH_TOKEN: ${{ secrets.GH_COMMIT_CHECK_TOKEN }}
+      - name: Checkout Associated PR ${{ github.event.issue.number }}
         run: gh pr checkout ${{ github.event.issue.number }}
 
-
-        # TODO: Consolidate Minor and Major steps, allows deletion of the Result step
-      - name: Minor
-        if: contains(github.event.comment.body, 'minor')
-        id: minor
+      - name: VERSION
+        id: bump
         run: |
           version=$(cat VERSION)
           regex="(.+-.+)-([0-9]+)\.([0-9]+)"
@@ -41,8 +42,18 @@ jobs:
             echo "::error::Invalid version format in VERSION file!"
             exit 1
           fi
-          new_minor_version=$((minor_version + 1))
-          new_version="${config_info}-${major_version}.${new_minor_version}"
+
+          if [[ "${{ contains(github.event.comment.body, 'minor') }}" == "true" ]]; then
+            new_minor_version=$((minor_version + 1))
+            new_version="${config_info}-${major_version}.${new_minor_version}"
+          else if [[ ${{ contains(github.event.comment.body, 'major') }} == "true" ]]; then
+            new_major_version=$((major_version + 1))
+            new_minor_version=0
+            new_version="${config_info}-${new_major_version}.${new_minor_version}"
+          else
+            echo "::error::Comment was not of the form: '!bump [major|minor]'"
+            exit 1
+          fi
           echo "$new_version" > VERSION
 
           git config user.name github-actions
@@ -52,59 +63,17 @@ jobs:
 
           echo "before=$version" >> $GITHUB_OUTPUT
           echo "after=$new_version" >> $GITHUB_OUTPUT
-
-      - name: Major
-        if: contains(github.event.comment.body, 'major')
-        id: major
-        run: |
-          version=$(cat VERSION)
-          regex="(.+-.+)-([0-9]+)\.([0-9]+)"
-          if [[ $version =~ $regex ]]; then
-            config_info="${BASH_REMATCH[1]}"
-            major_version="${BASH_REMATCH[2]}"
-            minor_version="${BASH_REMATCH[3]}"
-          else
-            echo "::error::Invalid version format in VERSION file!"
-            exit 1
-          fi
-          new_major_version=$((major_version + 1))
-          new_minor_version=0
-          new_version="${config_info}-${new_major_version}.${new_minor_version}"
-          echo "$new_version" > VERSION
-
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git commit -am "Bumped VERSION to $new_version as part of ${{ env.RUN_URL }}"
-          git push
-
-          echo "before=$version" >> $GITHUB_OUTPUT
-          echo "after=$new_version" >> $GITHUB_OUTPUT
-
-      - name: Results
-        id: result
-        # collate the results of either of the above commands
-        run: |
-          if [[ "${{ steps.major.outcome }}" == "success" ]]; then
-            echo "before=${{ steps.major.outputs.before }}" >> $GITHUB_OUTPUT
-            echo "after=${{ steps.major.outputs.after }}" >> $GITHUB_OUTPUT
-          elif [[ "${{ steps.minor.outcome }}" == "success" ]]; then
-            echo "before=${{ steps.minor.outputs.before }}" >> $GITHUB_OUTPUT
-            echo "after=${{ steps.minor.outputs.after }}" >> $GITHUB_OUTPUT
-          else
-            echo "::error::Bumping failed. Either the '!bump' command isn't typed out correctly, or there was an error earlier."
-            exit 1
-          fi
 
       - name: Comment Success
-        if: steps.result.outcome == 'success'
-        uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308  #v2.4.3
-        with:
-          message: |
-            :white_check_mark: Version bumped from `${{ steps.result.outputs.before }}` to `${{ steps.result.outputs.after }}` :white_check_mark:
+        env:
+          BODY: |
+            :white_check_mark: Version bumped from `${{ steps.bump.outputs.before }}` to `${{ steps.bump.outputs.after }}` :white_check_mark:
+        run:
+          gh pr comment --body "${{ env.BODY }}"
 
       - name: Comment Failure
-        if: failure() || steps.result.outcome == 'failure'
-        uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308  #v2.4.3
-        with:
-          message: |
+        if: failure()
+        env:
+          BODY: |
             :x: Failed to bump version, see ${{ env.RUN_URL }} :x:
+        run: gh pr comment --body "${{ env.BODY }}"
